version: "3"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  landingpage:
    build:
      context: landingpage
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - MoDaServer_network

networks:
  MoDaServer_network:
    driver: bridge
    external: true
